export const sampleData = [
  {
    PointKey: "1",
    PointTemplateName: "on/off",
    EquipmentName: "FCU 1",
    PointAddress: "FCU 1,On/Off,BV,0,N",
    OnlineStatus: "3",
    isAlarmed: "1",
    isReadOnly: "0",
    PointValue: "1",
    LastUpdatedTime: "2023-05-22 15:20",
  },
  {
    PointKey: "2",
    PointTemplateName: "Set Point",
    EquipmentName: "FCU 1",
    PointAddress: "FCU 1,Set Point,BV,0,N",
    OnlineStatus: "3",
    isAlarmed: "0",
    isReadOnly: "0",
    PointValue: "25",
    LastUpdatedTime: "2023-05-22 15:20",
  },
  {
    PointKey: "3",
    PointTemplateName: "Set-Temp",
    EquipmentName: "FCU 2",
    PointAddress: "FCU 2,SetTemp,BV,0,N",
    OnlineStatus: "1",
    isAlarmed: "0",
    isReadOnly: "0",
    PointValue: "27",
    LastUpdatedTime: "",
  },
  {
    PointKey: "4",
    PointTemplateName: "On_Off",
    EquipmentName: "Chiller 1",
    PointAddress: "localhost,Matrikon.OPC.Simulation.1,Write Only.UInt4",
    OnlineStatus: "2",
    isAlarmed: "1",
    isReadOnly: "1",
    PointValue: "0",
    LastUpdatedTime: "",
  },
  {
    PointKey: "5",
    PointTemplateName: "Chp 1",
    EquipmentName: "Chiller 1",
    PointAddress: "localhost,Matrikon.OPC.Simulation.1,@Clients",
    OnlineStatus: "1",
    isAlarmed: "0",
    isReadOnly: "1",
    PointValue: "20",
    LastUpdatedTime: "2022-07-07 13:17",
  },
  {
    PointKey: "6",
    PointTemplateName: "On_Off",
    EquipmentName: "Chiller 2",
    PointAddress: "localhost,Matrikon.OPC.Simulation.1,Write Only.Money",
    OnlineStatus: "2",
    isAlarmed: "0",
    isReadOnly: "1",
    PointValue: "0",
    LastUpdatedTime: "",
  },
];
